dist: bionic
language: generic
sudo: required
cache:
  directories:
  - /usr/local/bin/
branches:
  only:
  - code
  - configuration
services:
  - docker

script:
  - echo "TravisCI startred demo1"
  - chmod a+rx ./build.sh
  - ./build.sh all
  
