apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: development
  namespace: argocd
spec:
  generators:
  - list:
      elements:
        - namespace: argocd
  template:
    metadata:
      name: 'argocd-nginxapp'
    spec:
      project: default
      destination:
        namespace: 'argocd'
        server: https://kubernetes.default.svc
      source:
        path: resources/nginxapp
        repoURL: https://github.com/cbagade/argocd-repo.git
        targetRevision: code
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        retry:
          limit: 3
          backoff:
            duration: 2m
            factor: 3
            maxDuration: 8m'
