apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: development
spec:
  generators:
  - git:
      files:
      - path: configurations/development/cluster-config.yaml
      repoURL: https://github.com/Rohita83/argocd-repo
      revision: configuration
  template:
    metadata:
      name: '{{cluster.dev_project_name}}'
    spec:
      project: psl-argoproj-resources
      destination:
        namespace: argocd
        server: https://kubernetes.default.svc
      source:
        path: apps
        plugin:
          name: argocd-vault-plugin-helm-custom        
          env:
          - name: HELM_VALUES
            value: --values values.yaml
          - name: HELM_ARGS
            value: >-
              --set helloworld_app.label_from_cluster={{helloworld_app.label_from_cluster}}
              --set helloworld_app.replicas={{helloworld_app.replicas}}
        repoURL: https://github.com/Rohita83/argocd-repo
        targetRevision: d828f27eac64893ad43c60d98a411133c9a90841
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        retry:
          limit: 3
          backoff:
            duration: 2m
            factor: 3
            maxDuration: 8m
