apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: development
  namespace: argocd
spec:
  generators:
  - list:
      elements:
        - namespace: argocd
  - git:
      files:
      - path: configurations/development/cluster-config.yaml
      repoURL: https://github.com/Rohita83/argocd-repo
      revision: configuration     
  template:
    metadata:
      name: 'argocd-nginxapp-dev'
    spec:
      project: psl-argoproj-resources
      destination:
        namespace: argocd
        server: https://kubernetes.default.svc
      source:
        path: apps
        plugin:
          env:
          - name: HELM_VALUES
            value: --values values.yaml
          - name: HELM_ARGS
            value: >-
              --set helloworld_app.resources.requests.memory={{helloworld_app.resources.requests.memory}}
              --set helloworld_app.resources.requests.cpu={{helloworld_app.resources.requests.cpu}}
              --set helloworld_app.resources.limits.memory={{helloworld_app.resources.limits.memory}}
              --sethelloworld_app.resources.limits.cpu={{helloworld_app.resources.limits.cpu}}
          name: argocd-vault-plugin-helm-custom
        repoURL: https://github.com/Rohita83/argocd-repo
        targetRevision: code
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        retry:
          limit: 3
          backoff:
            duration: 2m
            factor: 3
            maxDuration: 8m
