apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: development
  namespace: argocd
spec:
  generators:
  - list:
      elements:
        - namespace: argocd
  template:
    metadata:
      name: 'argocd-nginxapp'
    spec:
      project: default
      destination:
        namespace: 'argocd'
        server: https://kubernetes.default.svc
      source:
        path: apps
        repoURL: https://github.com/cbagade/argocd-repo
        targetRevision: code
