apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: development
  namespace: argocd
spec:
  generators:
  - list:
      elements:
        - namespace: argocd
  template:
    metadata:
      name: 'argocd-nginxapp-dev'
    spec:
      project: psl-argoproj-resources
      destination:
        namespace: argocd
        server: https://kubernetes.default.svc
      source:
        path: apps
        repoURL: https://github.com/Rohita83/argocd-repo
        targetRevision: c3ae04c3850e70ed1223351b6f5c1227db33c346
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        retry:
          limit: 3
          backoff:
            duration: 2m
            factor: 3
            maxDuration: 8m
