repoURL: https://github.com/Rohita83/argocd-repo
# targetRevision: test-code-branch
environment: dev
cluster:
  url: https://kubernetes.default.svc
metadata:
  project: psl-argoproj-resources
  namespace: argocd
  argocd_namespace: argocd
  nginx_app_namespace: eks-sample-app
