repoURL: https://github.com/cbagade/argocd-repo
targetRevision: code
environment: dev
cluster:
  url: https://kubernetes.default.svc
metadata:
  project: default
  namespace: argocd
  argocd_namespace: argocd
  nginx-app_namespace: argocd
