repoURL: https://github.com/Rohita83/argocd-repo
targetRevision: code
environment: dev
cluster:
  url: https://kubernetes.default.svc
metadata:
  project: psl-argoproj-resources
  argocd_namespace: argocd-worker
  nginx_app_namespace: eks-sample-app
