cluster:
  name: argocd-project
  shortname: argocd-project
metadata:
  argocd_namespace: argocd
  helloworld_app_namespace: helloworld-app-ns

helloworld_app:
  replicas: 2
  resources:
    limits:
      cpu: '500m'
      memory: '256Mi'
    requests:
      cpu: '100m'
      memory: '128Mi'